### ISSUE TITLE
Improve ESLint

### ISSUE THREAD

**Issue by therungg** [therungg/therun-frontend#11]
There's some ESLint rules that shouldn't have to be turned off, and there are a bunch of ESLint plugins I'd like to use.

**Comment by francis-robert** [comment]
Do you want [typescript-eslint](https://typescript-eslint.io/) added to the project?

Are there other rules or plugins you had in mind?

**Comment by therungg** [comment]
Some typescript enforcing would be great, maybe to start just for staged changes. Enforcing no typescript errors for the entire project is a bit farfetched for now imo.

As far as other plugins, I'd like to use some more robust linter, but can't really decide which of the millions (https://github.com/dustinspecker/awesome-eslint) to prefer. Suggestions are welcome!
