### ISSUE TITLE
Pagination on leaderboards

### ISSUE THREAD

**Issue by therungg** [therungg/therun-frontend#21]
The leaderboards have no pagination, and are sometimes 200+ users long, so that becomes a bit of a mess. They could use searching and pagination. See other tables with pagination and searching (eg tournament runs) for examples

**Comment by christofkern** [comment]
i agree, in the end if theres one table with pagination that works really well it can be copied quite easily, so I want to look into creating one with an external library and then after that can look into refactoring all tables/or make the one under 
components/tournament/tournament-runs.tsx as a importable component, I dont really mind, since I like the looks of it, even though i dont understand why there are those "..." buttons that dont do anything.

Just tell me what you prefer, honestly :D im down for both

**Comment by christofkern** [comment]
also when filtering the text is behaving a bit weirdly, the numbers should be swapped I believe 🤣 
![image](https://github.com/therungg/therun-frontend/assets/79835127/998deb6f-c016-4740-8ea8-87ec2a7bab88)

**Comment by christofkern** [comment]
I just implemented it for the Event leaderboards, but in a way that it can be used everywhere basically, so kinda tackling #3 as well. All the functionality is there, searching, navigation, and working flawlessly, even debounced the search for 1s (so we dont permanently change the view, think #4 has this issue as well) The only thing im not too happy about is the positioning, cause I like it more if its under the table, but if the table gets too long its kinda annoying, 
so the option would be:
- to hard limit the entries
- just do it under the table
- if there are more than 20 entries have it on top and on bottom

so maybe we can start a discussion what fits the best / what UI we want, but the functionality exists now 🤷 .

![image](https://github.com/therungg/therun-frontend/assets/79835127/84801983-101f-4d62-b58c-15f76ae8e66e)

**Comment by christofkern** [comment]
https://github.com/christofkern/therun-frontend/tree/pagination_overhaul
if you want to try it out

**Comment by therungg** [comment]
Hey! Thanks so much for the effort. Your code looks great!

However, as I mentioned yesterday, I don't see the benefit in a *new* pagination solution. The point of this issue was to just reuse the current pagination logic that's used in other components, to avoid that there are simultaneously 2 seperate pagination solutions.

Afterward, in #3, it's the idea to completely overhaul every table with new pagination/searching/sorting, but to use a prebuilt solution, for example something like https://www.npmjs.com/package/react-data-table-component, which has every functionality we'd ever need and more out of the box.

Let me know your thoughts and how you view this :)!

**Comment by christofkern** [comment]
i agree, I just wasnt that aware of what is out there. Heres an implementation with the react data table component library.
it does not have a built-in search functionality as far as I can tell from the docs, but there is an example which does that as well.

In general it looks quite clean, and was very easy to implement. so why not :D


![image](https://github.com/therungg/therun-frontend/assets/79835127/0b315e7c-43e2-45f9-885f-2e7e48d3bad9)
