### ISSUE TITLE
Remove anchors from <Link> tags

### ISSUE THREAD

**Issue by francis-robert** [therungg/therun-frontend#36]
Next13 updated how Link tags work. They no longer allow `<a>` tags within the Links and should be removed. The codemod added a `legacyBehavior` prop for the components it couldn't remove the anchors automatically.

[nextjs13 migration docs](https://nextjs.org/docs/pages/building-your-application/upgrading/codemods#remove-a-tags-from-link-components)

              Hmm, didn't the codemod catch this one? I'm reading the `<a>` tag within link should be just removed. Not sure what's better, because that might come with some regression

_Originally posted by @therungg in https://github.com/therungg/therun-frontend/pull/33#discussion_r1197075421_
            

## Acceptance criteria

- Identify all `Link` tags with nested `a` tags
- Remove the `a` tags as they are automatically created by the `Link`
- Remove the `legacyBehavior` prop from the `Link` if it has been added
- Test the links

**Comment by Nkiriobasi** [comment]
I'll work on this

**Comment by therungg** [comment]
Fixed by @Nkiriobasi
