### ISSUE TITLE
Ended At time for runs does not properly account for timezones

### ISSUE THREAD

**Issue by francis-robert** [therungg/therun-frontend#60]
Some times are being displayed in the future

![image](https://github.com/therungg/therun-frontend/assets/87673558/bd64c638-b3aa-495f-892d-8e21dc19cfa8)

**Comment by francis-robert** [comment]
There's already [momentjs](https://momentjs.com/) and [luxon](https://moment.github.io/luxon/#/) installed as dependencies to the project. I think those would be a good place to start to avoid needing to install additional depenendencies.

**Comment by RedLime** [comment]
yeah SpeedRunIGT has messed up timezone with upload the run, it will be fixed in new release.

**Comment by joeyamst** [comment]
Thank you, @RedLime!

**Comment by RedLime** [comment]
It has been fixed in latest version of SpeedRunIGT. However, there's many people still use the old version, so the same problem may occur

**Comment by francis-robert** [comment]
@therungg what do you think about adding a UI component that displays to the user uploading MC splits with times in the future notifying them of the suspected issue and recommending they update their client?

Might just be an unneeded edge case?

**Comment by therungg** [comment]
Don't think thats necessary. Probably not many people from MC visit the site regularly anyway honestly, so it won't be very effective either. I filter out all the *in the future* runs now, So they won't be visible anyway.

Going to close this issue

**Comment by RedLime** [comment]
yeah SpeedRunIGT have specific `User-Agent` http request header to `SpeedRunIGT/{VERSION}`, so it can be detect an old version by using it.
