### ISSUE TITLE
Improve scroll bar looks

### ISSUE THREAD

**Issue by therungg** [therungg/therun-frontend#84]
Right now, on Chromium based browser, the scroll bars for the livesplit view on the live page look TERRIBLE. On firefox it's fine. They could use a revamp.

![image](https://github.com/therungg/therun-frontend/assets/115251302/430bcf18-78cb-4eb4-b501-86978e3d4c9d)

**Comment by zoglo** [comment]
Commited a change to rework scrollbar styles

See: #86 for more information and screenshots
